"""
Hardware-aware profiling for the v1.0-final face verification pipeline.

Times the same pipeline that `src.cli` runs in production via the
`src.verifier.FaceVerifier` class:

    1. preprocess  : disk I/O + center-crop + resize  (per image)
    2. embed       : FaceNet forward pass             (per image, batched)
    3. score       : cosine similarity                (per pair)
    4. end-to-end  : load + load + embed(batch=2) + score  (per pair)

For each stage we report median, mean, p95 over `--reps` repetitions, and we
sweep batch sizes for the embedding stage.

Outputs (under reports/profiling/):
    - latency_summary.json   machine-readable numbers
    - latency_summary.md     human-readable table for the profiling report

The script uses real LFW images so that the preprocessing stage reflects
realistic JPEG decode + crop cost, not a synthetic in-memory benchmark.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import statistics
import sys
import time
from typing import Callable, List

import numpy as np

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

from src.similarity import cosine_similarity  # noqa: E402
from src.verifier import load_and_preprocess  # noqa: E402

LFW_BASE = os.path.join(PROJECT_ROOT, "data", "lfw")
DEFAULT_OUT_DIR = os.path.join(PROJECT_ROOT, "reports", "profiling")


def collect_image_paths(n: int) -> List[str]:
    paths: List[str] = []
    for identity in sorted(os.listdir(LFW_BASE)):
        idir = os.path.join(LFW_BASE, identity)
        if not os.path.isdir(idir):
            continue
        for fname in sorted(os.listdir(idir)):
            if fname.lower().endswith(".jpg"):
                paths.append(os.path.join(idir, fname))
                if len(paths) >= n:
                    return paths
    if len(paths) < n:
        raise RuntimeError(
            f"only found {len(paths)} LFW images under {LFW_BASE}; "
            f"need at least {n}. Run scripts/plumbing/ingest_lfw.py first."
        )
    return paths


def time_call(fn: Callable[[], object], reps: int) -> List[float]:
    samples = []
    for _ in range(reps):
        t0 = time.perf_counter()
        fn()
        samples.append(time.perf_counter() - t0)
    return samples


def summarize(samples_s: List[float]) -> dict:
    samples_ms = [s * 1000.0 for s in samples_s]
    return {
        "n": len(samples_ms),
        "mean_ms": float(statistics.mean(samples_ms)),
        "median_ms": float(statistics.median(samples_ms)),
        "p95_ms": float(np.percentile(samples_ms, 95)),
        "min_ms": float(min(samples_ms)),
        "max_ms": float(max(samples_ms)),
    }


def env_info() -> dict:
    info = {
        "platform": platform.platform(),
        "python": sys.version.split()[0],
        "processor": platform.processor(),
    }
    try:
        import psutil  # noqa: WPS433
        freq = psutil.cpu_freq()
        info.update({
            "logical_cores": psutil.cpu_count(logical=True),
            "physical_cores": psutil.cpu_count(logical=False),
            "cpu_max_mhz": freq.max if freq else None,
            "ram_gb": round(psutil.virtual_memory().total / 1024**3, 1),
        })
    except ImportError:
        pass
    try:
        import numpy as _np  # noqa: WPS433
        info["numpy"] = _np.__version__
    except ImportError:
        pass
    try:
        import tensorflow as _tf  # noqa: WPS433
        info["tensorflow"] = _tf.__version__
        info["tf_visible_gpus"] = [d.name for d in _tf.config.list_physical_devices("GPU")]
    except ImportError:
        info["tensorflow"] = None
    return info


def write_markdown(report: dict, out_path: str) -> None:
    env = report["environment"]
    lines = []
    lines.append("# Profiling Summary - v1.0-final\n")
    lines.append("Auto-generated by `scripts/profile_pipeline.py`. Do not edit by hand.\n")
    lines.append("## Environment\n")
    for k, v in env.items():
        lines.append(f"- **{k}**: {v}")
    lines.append("")
    lines.append(f"- **reps per measurement**: {report['reps']}")
    lines.append(f"- **warmup batches**: {report['warmup']}")
    lines.append(f"- **n images sampled from LFW**: {report['n_images']}")
    lines.append("")

    lines.append("## Per-stage latency (single image / single pair)\n")
    lines.append("| Stage | n | median (ms) | mean (ms) | p95 (ms) |")
    lines.append("| --- | ---: | ---: | ---: | ---: |")
    for stage in ("preprocess_per_image", "embed_per_image_b1", "score_per_pair"):
        s = report["per_stage"][stage]
        lines.append(
            f"| {stage} | {s['n']} | {s['median_ms']:.3f} | "
            f"{s['mean_ms']:.3f} | {s['p95_ms']:.3f} |"
        )
    lines.append("")

    lines.append("## Batch-size sensitivity (FaceNet embedding stage)\n")
    lines.append("| Batch size | median wall (ms) | per-image median (ms) | "
                 "throughput (img/s) |")
    lines.append("| ---: | ---: | ---: | ---: |")
    for entry in report["batch_sweep"]:
        lines.append(
            f"| {entry['batch_size']} | {entry['wall_median_ms']:.2f} | "
            f"{entry['per_image_median_ms']:.3f} | "
            f"{entry['throughput_img_per_s']:.1f} |"
        )
    lines.append("")

    lines.append("## End-to-end (per pair)\n")
    e2e = report["end_to_end_per_pair"]
    lines.append(
        f"- median **{e2e['median_ms']:.2f} ms**, mean {e2e['mean_ms']:.2f} ms, "
        f"p95 {e2e['p95_ms']:.2f} ms over {e2e['n']} pairs."
    )
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description="Profile the verification pipeline.")
    parser.add_argument("--reps", type=int, default=30,
                        help="Repetitions per single-stage measurement (default: 30).")
    parser.add_argument("--warmup", type=int, default=2,
                        help="Warmup batches before timing the embedding stage.")
    parser.add_argument("--n-images", type=int, default=64,
                        help="Number of LFW images to load for the experiment.")
    parser.add_argument("--batch-sizes", type=int, nargs="+",
                        default=[1, 2, 4, 8, 16, 32],
                        help="Batch sizes to sweep for the embedding stage.")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR,
                        help="Where to write latency_summary.{json,md}.")
    args = parser.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)
    print(f"[profile] gathering {args.n_images} LFW images ...")
    image_paths = collect_image_paths(args.n_images)

    print("[profile] loading FaceNet ...")
    from keras_facenet import FaceNet  # heavy import, deferred
    embedder = FaceNet()

    # Pre-decode all images once for the embed/score timings (we time
    # preprocess separately so JPEG decode does not pollute embed timings).
    print("[profile] preprocessing all sample images ...")
    decoded = np.stack([load_and_preprocess(p) for p in image_paths]).astype(np.uint8)
    assert decoded.shape == (args.n_images, 160, 160, 3), decoded.shape

    # ---- 1. preprocess (per image, off disk) -----------------------------
    print("[profile] timing preprocess (per image) ...")
    pre_samples: List[float] = []
    for path in image_paths[: args.reps]:
        t0 = time.perf_counter()
        load_and_preprocess(path)
        pre_samples.append(time.perf_counter() - t0)

    # ---- 2. embed @ batch=1 (per image) ---------------------------------
    print("[profile] warmup ...")
    for _ in range(args.warmup):
        embedder.embeddings(decoded[:8])

    print("[profile] timing embed (batch=1) ...")
    emb_b1_samples = time_call(
        lambda: embedder.embeddings(decoded[:1]),
        reps=args.reps,
    )

    # Pre-compute one set of embeddings for the score timing.
    embeddings_all = embedder.embeddings(decoded)
    assert embeddings_all.shape[0] == args.n_images

    # ---- 3. score (per pair) --------------------------------------------
    print("[profile] timing cosine score (per pair) ...")
    rng = np.random.default_rng(42)
    idx_a = rng.integers(0, args.n_images, size=args.reps)
    idx_b = rng.integers(0, args.n_images, size=args.reps)
    score_samples: List[float] = []
    for i, j in zip(idx_a, idx_b):
        ea = embeddings_all[i:i + 1]
        eb = embeddings_all[j:j + 1]
        t0 = time.perf_counter()
        cosine_similarity(ea, eb)
        score_samples.append(time.perf_counter() - t0)

    # ---- 4. batch sweep on embed ---------------------------------------
    print("[profile] sweeping batch sizes for embed ...")
    batch_sweep = []
    for bs in args.batch_sizes:
        if bs > args.n_images:
            continue
        for _ in range(args.warmup):
            embedder.embeddings(decoded[:bs])
        runs = 10
        wall_samples = time_call(
            lambda b=bs: embedder.embeddings(decoded[:b]),
            reps=runs,
        )
        wall_med_ms = statistics.median(wall_samples) * 1000.0
        per_img_med_ms = wall_med_ms / bs
        throughput = bs / (wall_med_ms / 1000.0)
        batch_sweep.append({
            "batch_size": bs,
            "runs": runs,
            "wall_median_ms": wall_med_ms,
            "per_image_median_ms": per_img_med_ms,
            "throughput_img_per_s": throughput,
        })
        print(f"   bs={bs:>3}  wall={wall_med_ms:7.2f} ms  "
              f"per_img={per_img_med_ms:6.3f} ms  "
              f"throughput={throughput:7.1f} img/s")

    # ---- 5. end-to-end (per pair) -------------------------------------
    print("[profile] timing end-to-end (per pair) ...")
    e2e_samples: List[float] = []
    pairs_to_time = min(args.reps, len(image_paths) // 2)
    for k in range(pairs_to_time):
        path_a = image_paths[2 * k]
        path_b = image_paths[2 * k + 1]
        t0 = time.perf_counter()
        a = load_and_preprocess(path_a)
        b = load_and_preprocess(path_b)
        embs = embedder.embeddings(np.stack([a, b]))
        cosine_similarity(embs[0:1], embs[1:2])
        e2e_samples.append(time.perf_counter() - t0)

    report = {
        "system_version": "v1.0-final",
        "environment": env_info(),
        "reps": args.reps,
        "warmup": args.warmup,
        "n_images": args.n_images,
        "per_stage": {
            "preprocess_per_image": summarize(pre_samples),
            "embed_per_image_b1": summarize(emb_b1_samples),
            "score_per_pair": summarize(score_samples),
        },
        "batch_sweep": batch_sweep,
        "end_to_end_per_pair": summarize(e2e_samples),
    }

    json_path = os.path.join(args.out_dir, "latency_summary.json")
    md_path = os.path.join(args.out_dir, "latency_summary.md")
    with open(json_path, "w") as f:
        json.dump(report, f, indent=2)
    write_markdown(report, md_path)

    print(f"\n[profile] wrote {json_path}")
    print(f"[profile] wrote {md_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
